### PR TITLE
Create azure-webapps-node.yml

### PR DESCRIPTION
**Pull request by CEEANPROJEC**

### CODE REVIEW

**Comment by CEEANPROJEC** [comment]
I agree to the  policy

**Comment by obrienwrite** [comment]
I have sole ownership of intellectual property rights to my Submissions
and I am not making Submissions in the course of work for my employer.

**Comment by CEEANPROJEC** [comment]
Yes  correct.

**Comment by DawnmarieDesJardins** [comment]
@obrienwrite @CEEANPROJEC 
Good morning.  This page is a library page for Microsoft Cloud Workshops that have been retired and are no longer being maintained or updated. The workshops are being kept for historical purposes, but no changes can be made.

**Comment by CEEANPROJEC** [comment]
Can you please mention pages that can be changed within Microsoft organization?.

**Pull request closed without merging**
